remote_theme: just-the-docs/just-the-docs

title: Member Handbook

color_scheme: light

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/farsetlabs/member-handbook"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
